version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]
    ignore:
      # Must match the version linfa uses.
      - dependency-name: ndarray
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
